stages:
    - tests
    - report

variables:
    STAGE: preprod

services:
    - docker:24.0.5-dind

run_tests:
    stage: tests
    image: docker:24.0.5
    script:
        # Запуск тестов с генерацией результатов Allure
        - docker compose up api-tests || true
        - docker run -v $(pwd)/allure-results:/allure-results -v $(pwd)/allure-report:/allure-report allure-framework/allure-cli:2.13.8 generate /allure-results --clean -o /allure-report
    artifacts:
        paths:
            - allure-report
        when: always  # Убедись, что артефакты загружаются даже при ошибках
        expire_in: 1 day

pages:
  stage: report
  needs:
    - run_tests
  script:
    - mkdir public
    # Проверка, существует ли директория allure-report
    - |
      if [ -d "allure-report" ]; then
        cp -r allure-report/* public
      else
        echo "Allure report not found!" && exit 1
      fi
  artifacts:
    when: always
    expire_in: never
    paths:
      - public
