image: node:16
stages:
  - test

run_tests:
  stage: test
  tags:
    - "dev-2"
  image: python
  artifacts:
        when: always
        expire_in: 5 days
        paths:
            - allure-report
  before_script:
    - pip install -r requirements.txt  
  script:
    - pytest -v --alluredir=allure-results
