stages:
  - test
  - report
variables:
  STAGE: preprod
services:
    - docker:24.0.5-dind
test:
  stage: test
  image: docker:24.0.5
  tags:
    - docker
 
  script:
    - docker compose up api-tests || true
  artifacts:
    paths:
      - allure-results
  when: on_success

report:
  stage: report
  image: openjdk:11
  tags:
    - docker
  needs:
    - test
  dependencies:
    - test
  script:
    - apt-get update && apt-get install -y unzip
    - apt-get -y install python3-pip
    - wget -qO allure-2.29.0.zip https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
    - unzip allure-2.29.0.zip -d /opt/allure
    - pip3 install allure-combine
    - /opt/allure/allure-2.29.0/bin/allure generate allure-results -o allure-report
    - allure-combine --dest ./report allure-report --auto-create-folders
  artifacts:
    paths:
      - report
    expire_in: 1 hour