stages:
  - test
  - report
variables:
  POETRY_HTTP_BASIC_GLOBERCE_USERNAME: $PYPI_USERNAME
  POETRY_HTTP_BASIC_GLOBERCE_PASSWORD: $PYPI_PASSWORD
  CLIENT_SECRET: $CLIENT_SECRET
  OPERATE_LOGIN: $OPERATE_LOGIN
  OPERATE_PASSWORD: $OPERATE_PASSWORD

test:
  stage: test
  image: python:3.11
  tags:
    - docker
  before_script:
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$HOME/.local/bin:$PATH"
    - poetry config http-basic.globerce $PYPI_USERNAME $PYPI_PASSWORD
    - poetry install --no-root

  script:
    - poetry run pytest -sv tests/blocks/test_full_except_aml.py::TestFullExceptAML::test_full_except_aml_110540004290 --alluredir=allure-results
  artifacts:
    paths:
      - allure-results
  when: manual

report:
  stage: report
  image: openjdk:11
  tags:
    - docker
  needs:
    - test
  dependencies:
    - test
  script:
    - apt-get update && apt-get install -y unzip
    - apt-get -y install python3-pip
    - wget -qO allure-2.29.0.zip https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.zip
    - unzip allure-2.29.0.zip -d /opt/allure
    - pip3 install allure-combine
    - /opt/allure/allure-2.29.0/bin/allure generate allure-results -o allure-report
    - allure-combine --dest ./report allure-report --auto-create-folders
  artifacts:
    paths:
      - report
    expire_in: 1 hour